server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: root

  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import:
      - "accounts-qa.yml"
      - "accounts-prod.yml"
  profiles:
    active:
      - "prod"

build:
  version: "3.0"


accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "{cipher}cb058cbf465aeccdb56b8956e58915b136a7e3349541e6c6d708a69dcc558ab5c403e2422f62da03df763a6fa91d6eb8"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
