server:
  port: 8900
spring:
  datasource:
    #url: jdbc:mysql://localhost:3309/loansdb
    #username: root
    #password: root

  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import:
      - "loans-qa.yml"
      - "loans-prod.yml"
  profiles:
    active:
      - "prod"
build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
